# from https://github.com/Repcz/Tool/blob/X/.github/workflows/Build.yml
#
# Final Workflow with Prioritized, Lossless Deduplication
#
name: Build
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:           # Triggers the workflow on a schedule
    - cron: "5 0,12 * * *"

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      SING_BOX_VERSION: "1.10.5"

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout ioss Repository
      uses: actions/checkout@v4
      with:
        repository: MESSIUINIMI/ioss
        path: ioss-repo

    # Step 2: Download all rule files
    - name: Download All Source Rules
      run: |
        mkdir -p ioss-repo/Ruleset
        files=(
          # --- SmartDNS Rules ---
          "ChinaMaxNoIP.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMaxNoIP/ChinaMaxNoIP.list"
          "Global.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list"
          "GlobalMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list"
          "apple-cn.list https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt"
          "AdvertisingLite.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list"
          "GitHub.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GitHub/GitHub.list"
          "ChinaIPs.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaIPs/ChinaIPs.list"
          "ChinaMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMedia/ChinaMedia.list"
          "Apple.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list"
          "JingDong.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/JingDong/JingDong.list"
          "bilibili.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/BiliBili/BiliBili.list"
          "Alibaba.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Alibaba/Alibaba.list"
          "Tencent.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Tencent/Tencent.list"
          "Adrules.conf https://github.com/Cats-Team/AdRules/raw/main/smart-dns.conf"
          "neodevhost.conf https://github.com/neodevpro/neodevhost/raw/master/smartdns.conf"
          # --- AdGuard Home Rules ---
          "adguard_filter_1.txt https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
          "neodev_adblocker.txt https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker"
          "cats_dns.txt https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
        )
        for item in "${files[@]}"; do
          set -- $item
          echo "Downloading: $1 from $2"
          curl -A "Mozilla/5.0" --connect-timeout 15 -f -L -o "ioss-repo/Ruleset/$1" "$2" || { echo "Download failed: $2"; exit 1; }
        done
        echo "All source files downloaded successfully."

    # Step 3: Process SmartDNS rules
    - name: Process SmartDNS Rules
      run: |
        set -e
        SRC_DIR="ioss-repo/Ruleset"
        echo "Processing *.list files..."
        for file in "$SRC_DIR"/*.list; do
          if [[ ! -f "$file" || ! -s "$file" ]]; then continue; fi
          TEMP_FILE="$file.tmp"
          case "$(basename "$file")" in
            "apple-cn.list") grep '^full:' "$file" | awk -F ':' '{print "-." $2}' > "$TEMP_FILE";;
            "ChinaIPs.list") grep -E '^IP-CIDR|^IP6-CIDR' "$file" | awk -F ',' '{ gsub("IP-CIDR,|IP6-CIDR,", ""); print "blacklist-ip " $1 }' > "$TEMP_FILE";;
            *) grep -E '^HOST|^HOST-SUFFIX' "$file" | awk -F ',' '{ if ($1 == "HOST") print "-." $2; else if ($1 == "HOST-SUFFIX") print "*." $2 }' > "$TEMP_FILE";;
          esac
          if [[ -s "$TEMP_FILE" ]]; then mv "$TEMP_FILE" "$file"; else rm -f "$TEMP_FILE"; fi
        done

        echo "Generating merged .conf and .list files..."
        CONF_MERGED="$SRC_DIR/Adrulesnoedevhost.conf"
        LIST_MERGED="$SRC_DIR/Adrulesnoedevhost.list"
        awk 'BEGIN { FS = "/" } NR==FNR { if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 } next } { if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 } } END { for (domain in lines) { print lines[domain] } }' "$SRC_DIR/Adrules.conf" "$SRC_DIR/neodevhost.conf" | sort > "$CONF_MERGED"
        awk -F'/' '{print $2}' "$CONF_MERGED" > "$LIST_MERGED"
        echo "Generated merged files successfully."
        
    # Step 4: Process AdGuard Home rules with prioritized deduplication
    - name: Process AdGuard Home Rules
      run: |
        set -e
        SRC_DIR="ioss-repo/Ruleset"
        
        echo "Merging AdGuard Home rules with strict priority and no modification..."
        
        # 核心逻辑: 使用 awk 按顺序处理文件，只添加新行，不修改任何内容
        awk '!seen[$0]++' \
          "$SRC_DIR/cats_dns.txt" \
          "$SRC_DIR/neodev_adblocker.txt" \
          "$SRC_DIR/adguard_filter_1.txt" \
          > "$SRC_DIR/Adset.txt"
        
        echo "Generated Adset.txt successfully."
        echo "Final Adset.txt total line count:"
        wc -l "$SRC_DIR/Adset.txt"

    # Step 5: Deploy all final rules
    - name: Deploy All Final Rules
      run: |
        set -e
        SRC_DIR="ioss-repo/Ruleset"
        
        # Deploy SmartDNS Rules
        SMARTDNS_DEST_DIR="ioss-repo/Smartdns/Rules"
        echo "Deploying final SmartDNS rules to $SMARTDNS_DEST_DIR"
        rm -rf "$SMARTDNS_DEST_DIR"
        mkdir -p "$SMARTDNS_DEST_DIR"
        cp "$SRC_DIR"/*.list "$SMARTDNS_DEST_DIR/"
        cp "$SRC_DIR/Adrulesnoedevhost.conf" "$SMARTDNS_DEST_DIR/"
        
        # Deploy AdGuard Home Rules
        ADG_DEST_DIR="ioss-repo/AdGuardHome/Rule"
        echo "Deploying final AdGuard Home rules to $ADG_DEST_DIR"
        rm -rf "$ADG_DEST_DIR"
        mkdir -p "$ADG_DEST_DIR"
        cp "$SRC_DIR/Adset.txt" "$ADG_DEST_DIR/"
        
        echo "--- Verification ---"
        echo "Contents of SmartDNS destination:"
        ls -l "$SMARTDNS_DEST_DIR"
        echo "Contents of AdGuard Home destination:"
        ls -l "$ADG_DEST_DIR"
        
    # Step 6: Install and configure sing-box
    - name: Install and Configure sing-box
      run: |
        echo "Downloading and installing sing-box..."
        curl -sL -o sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz"
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/
        rm -rf sing-box.tar.gz sing-box-${SING_BOX_VERSION}-linux-amd64
        sing-box version
        echo "Compiling .srs rule sets..."
        for file in ioss-repo/Sing-box/ruleset/*.json; do
            sing-box rule-set compile "$file" -o "${file%.json}.srs"
        done
        rm -rf ioss-repo/Ruleset

    # Step 7: 将更新推送到 ioss 仓库
    - name: Commit and Push Updates
      run: |
        cd ioss-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "No changes to commit."
        fi

    # Step 8: 清理历史 Workflow Runs
    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
