# from https://github.com/Repcz/Tool/blob/X/.github/workflows/Build.yml
name: Build
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:           # Triggers the workflow on a schedule
    - cron: "5 0,12 * * *"

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      SING_BOX_VERSION: "1.10.5"

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout ioss Repository
      uses: actions/checkout@v4
      with:
        repository: MESSIUINIMI/ioss
        path: ioss-repo

    # Step 2: Download all rule files sequentially
    - name: Download All Source Rules
      run: |
        mkdir -p ioss-repo/Ruleset
        files=(
          # --- SmartDNS Rules ---
          "ChinaMaxNoIP.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMaxNoIP/ChinaMaxNoIP.list"
          "Global.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list"
          "GlobalMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list"
          "apple-cn.list https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt"
          "AdvertisingLite.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list"
          "GitHub.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GitHub/GitHub.list"
          "ChinaIPs.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaIPs/ChinaIPs.list"
          "ChinaMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMedia/ChinaMedia.list"
          "Apple.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list"
          "JingDong.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/JingDong/JingDong.list"
          "bilibili.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/BiliBili/BiliBili.list"
          "Alibaba.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Alibaba/Alibaba.list"
          "Tencent.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Tencent/Tencent.list"
          "Adrules.conf https://github.com/Cats-Team/AdRules/raw/main/smart-dns.conf"
          "neodevhost.conf https://github.com/neodevpro/neodevhost/raw/master/smartdns.conf"
          # --- AdGuard Home Rules ---
          "adguard_filter_1.txt https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
          "neodev_adblocker.txt https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker"
          "cats_dns.txt https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
        )
        for item in "${files[@]}"; do
          set -- $item
          echo "Downloading: $1 from $2"
          curl -A "Mozilla/5.0" --connect-timeout 15 -f -L -o "ioss-repo/Ruleset/$1" "$2" || { echo "Download failed: $2"; exit 1; }
        done
        echo "All source files downloaded successfully."

    # Step 3: Process all downloaded files
    - name: Process, Merge, and Generate All Rule Files
      run: |
        set -e
        SRC_DIR="ioss-repo/Ruleset"

        # --- Part 1: Process SmartDNS *.list files ---
        echo "Processing SmartDNS *.list files..."
        for file in "$SRC_DIR"/*.list; do
          if [[ ! -f "$file" || ! -s "$file" ]]; then continue; fi
          TEMP_FILE="$file.tmp"
          case "$(basename "$file")" in
            "apple-cn.list") grep '^full:' "$file" | awk -F ':' '{print "-." $2}' > "$TEMP_FILE";;
            "ChinaIPs.list") grep -E '^IP-CIDR|^IP6-CIDR' "$file" | awk -F ',' '{ gsub("IP-CIDR,|IP6-CIDR,", ""); print "blacklist-ip " $1 }' > "$TEMP_FILE";;
            *) grep -E '^HOST|^HOST-SUFFIX' "$file" | awk -F ',' '{ if ($1 == "HOST") print "-." $2; else if ($1 == "HOST-SUFFIX") print "*." $2 }' > "$TEMP_FILE";;
          esac
          if [[ -s "$TEMP_FILE" ]]; then mv "$TEMP_FILE" "$file"; else rm -f "$TEMP_FILE"; fi
        done

        # --- Part 2: Generate SmartDNS merged .conf and .list files ---
        echo "Generating SmartDNS merged files..."
        awk 'BEGIN { FS = "/" } NR==FNR { if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 } next } { if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 } } END { for (domain in lines) { print lines[domain] } }' "$SRC_DIR/Adrules.conf" "$SRC_DIR/neodevhost.conf" | sort > "$SRC_DIR/Adrulesnoedevhost.conf"
        awk -F'/' '{print $2}' "$SRC_DIR/Adrulesnoedevhost.conf" > "$SRC_DIR/Adrulesnoedevhost.list"
        echo "Generated SmartDNS merged files successfully."

        # --- Part 3: Generate AdGuard Home merged file ---
        echo "Generating AdGuard Home merged file (Adset.txt)..."
        # 优化: 将新生成的 Adset.txt 也统一保存在 Ruleset 目录中
        cat "$SRC_DIR/adguard_filter_1.txt" "$SRC_DIR/neodev_adblocker.txt" "$SRC_DIR/cats_dns.txt" \
        | grep -vE '^!|^#|^\s*$' \
        | sort -u > "$SRC_DIR/Adset.txt"
        echo "Generated Adset.txt successfully in source directory."
        wc -l "$SRC_DIR/Adset.txt"

    # Step 4: Deploy all final rules to their destinations
    - name: Deploy All Final Rules
      run: |
        set -e
        SRC_DIR="ioss-repo/Ruleset"
        
        # --- Part 1: Deploy SmartDNS Rules ---
        SMARTDNS_DEST_DIR="ioss-repo/Smartdns/Rules"
        echo "Deploying final SmartDNS rules to $SMARTDNS_DEST_DIR"
        rm -rf "$SMARTDNS_DEST_DIR"
        mkdir -p "$SMARTDNS_DEST_DIR"
        cp "$SRC_DIR"/*.list "$SMARTDNS_DEST_DIR/"
        cp "$SRC_DIR/Adrulesnoedevhost.conf" "$SMARTDNS_DEST_DIR/"
        echo "SmartDNS rules deployed. Verifying contents:"
        ls -l "$SMARTDNS_DEST_DIR"

        # --- Part 2: Deploy AdGuard Home Rules (New) ---
        ADG_DEST_DIR="ioss-repo/AdGuardHome/Rule"
        echo "Deploying final AdGuard Home rules to $ADG_DEST_DIR"
        rm -rf "$ADG_DEST_DIR"
        mkdir -p "$ADG_DEST_DIR"
        cp "$SRC_DIR/Adset.txt" "$ADG_DEST_DIR/"
        echo "AdGuard Home rules deployed. Verifying contents:"
        ls -l "$ADG_DEST_DIR"
        
    # Step 5: Install and configure sing-box
    - name: Install and Configure sing-box
      run: |
        echo "Downloading and installing sing-box..."
        curl -sL -o sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz"
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/
        rm -rf sing-box.tar.gz sing-box-${SING_BOX_VERSION}-linux-amd64
        sing-box version
        echo "Compiling .srs rule sets..."
        for file in ioss-repo/Sing-box/ruleset/*.json; do
            sing-box rule-set compile "$file" -o "${file%.json}.srs"
        done
        # 清理所有临时的源文件和中间文件
        rm -rf ioss-repo/Ruleset

    # Step 6: Commit and push changes
    - name: Commit and Push Updates
      run: |
        cd ioss-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "No changes to commit."
        fi

    # Step 7: 清理历史 Workflow Runs
    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
