# from https://github.com/Repcz/Tool/blob/X/.github/workflows/Build.yml
name: Build
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:           # Triggers the workflow on a schedule
    - cron: "5 0,12 * * *"

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      SING_BOX_VERSION: "1.10.5"

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout ioss Repository
      uses: actions/checkout@v4
      with:
        repository: MESSIUINIMI/ioss
        path: ioss-repo

    # Step 2: Download rule files sequentially for stability
    - name: Download Rules Sequentially
      run: |
        mkdir -p ioss-repo/Ruleset
        files=(
          "ChinaMaxNoIP.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMaxNoIP/ChinaMaxNoIP.list"
          "Global.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list"
          "GlobalMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list"
          "apple-cn.list https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt"
          "AdvertisingLite.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list"
          "GitHub.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GitHub/GitHub.list"
          "ChinaIPs.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaIPs/ChinaIPs.list"
          "ChinaMedia.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMedia/ChinaMedia.list"
          "Apple.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list"
          "JingDong.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/JingDong/JingDong.list"
          "bilibili.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/BiliBili/BiliBili.list"
          "Alibaba.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Alibaba/Alibaba.list"
          "Tencent.list https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Tencent/Tencent.list"
          "Adrules.conf https://github.com/Cats-Team/AdRules/raw/main/smart-dns.conf"
          "neodevhost.conf https://github.com/neodevpro/neodevhost/raw/master/smartdns.conf"
        )

        # 修复：换回稳定可靠的 for 循环方式进行下载
        for item in "${files[@]}"; do
          # 使用 set 命令安全地分割文件名和 URL
          set -- $item
          local_name=$1
          remote_url=$2
          
          echo "Downloading: $local_name from $remote_url"
          curl -A "Mozilla/5.0" --connect-timeout 15 -f -L -o "ioss-repo/Ruleset/$local_name" "$remote_url" || { echo "Download failed: $remote_url"; exit 1; }
        done
        
        echo "All files downloaded successfully."

    # Step 3: Process all rule files in a single, consolidated step
    - name: Process, Merge, and Generate Rule Files
      run: |
        RULES_DIR="ioss-repo/Ruleset"

        # --- Part 1: Process *.list files ---
        echo "Processing *.list files..."
        for file in "$RULES_DIR"/*.list; do
          if [[ ! -f "$file" || ! -s "$file" ]]; then
            echo "Skipping non-existent or empty file: $file"
            continue
          fi
          
          TEMP_FILE="$file.tmp"
          case "$(basename "$file")" in
            "apple-cn.list")
              grep '^full:' "$file" | awk -F ':' '{print "-." $2}' > "$TEMP_FILE"
              ;;
            "ChinaIPs.list")
              grep -E '^IP-CIDR|^IP6-CIDR' "$file" | awk -F ',' '{ gsub("IP-CIDR,|IP6-CIDR,", ""); print "blacklist-ip " $1 }' > "$TEMP_FILE"
              ;;
            *)
              grep -E '^HOST|^HOST-SUFFIX' "$file" | awk -F ',' '{ if ($1 == "HOST") print "-." $2; else if ($1 == "HOST-SUFFIX") print "*." $2 }' > "$TEMP_FILE"
              ;;
          esac
          
          if [[ -s "$TEMP_FILE" ]]; then
            mv "$TEMP_FILE" "$file"
          else
            echo "Warning: Processed file $file is empty. Original file retained."
            rm -f "$TEMP_FILE"
          fi
        done

        # --- Part 2: Merge *.conf files and create domain-only list ---
        echo "Merging and deduplicating *.conf files..."
        CONF_MERGED="$RULES_DIR/Adrulesnoedevhost.conf"
        LIST_MERGED="$RULES_DIR/Adrulesnoedevhost.list"

        awk '
          BEGIN { FS = "/" }
          NR==FNR {
              if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 }
              next
          }
          {
              if ($0 ~ /^address \// && !seen[$2]++) { lines[$2] = $0 }
          }
          END {
              for (domain in lines) { print lines[domain] }
          }
        ' "$RULES_DIR/Adrules.conf" "$RULES_DIR/neodevhost.conf" | sort > "$CONF_MERGED"

        awk -F'/' '{print $2}' "$CONF_MERGED" > "$LIST_MERGED"
        
        echo "Rule generation complete."
        echo "--- Verification: Final Rule Counts ---"
        wc -l "$CONF_MERGED"
        wc -l "$LIST_MERGED"
        echo "------------------------------------"

    # Step 4: Copy generated files to the final destination
    - name: Deploy Rules to Smartdns Directory
      run: |
        DEST_DIR="ioss-repo/Smartdns/Rules"
        SRC_DIR="ioss-repo/Ruleset"

        rm -rf "$DEST_DIR"
        mkdir -p "$DEST_DIR"

        cp "$SRC_DIR"/*.list "$DEST_DIR/"
        cp "$SRC_DIR"/Adrulesnoedevhost.conf "$DEST_DIR/"
        
        echo "All final rule files have been deployed."
        ls -l "$DEST_DIR"

    # Step 5: Install and configure sing-box (always re-downloading)
    - name: Install and Configure sing-box
      run: |
        echo "Downloading and installing sing-box..."
        curl -sL -o sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz"
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/
        
        # Clean up installation files
        rm -rf sing-box.tar.gz sing-box-${SING_BOX_VERSION}-linux-amd64
        
        sing-box version

        # Compile rules
        echo "Compiling .srs rule sets..."
        for file in ioss-repo/Sing-box/ruleset/*.json; do
            sing-box rule-set compile "$file" -o "${file%.json}.srs"
        done
        
        # Clean up the downloaded source rules
        rm -rf ioss-repo/Ruleset

    # Step 6: Commit and push changes to the repository
    - name: Commit and Push Updates
      run: |
        cd ioss-repo
        if ! git diff --quiet; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
        else
          echo "No changes to commit."
        fi

    # Step 7: Clean up old workflow runs
    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        retain_days: 1
        keep_minimum_runs: 2
